Conform PathComponent to Equatable
vapor/routing-kit pull request #129
Opened 2023-12-17 06:59 UTC by marius-se

Conforms `PathComponent` to Equatable. Related to [this PR](https://github.com/swift-server/swift-openapi-vapor/pull/13#issuecomment-1841643073)

2023-12-17 07:03 UTC, gwynne commented
Might as well conform it to `Hashable` (which itself requires `Equatable`, so no need to conform to both)

2023-12-17 07:05 UTC, marius-se commented
@gwynne done ✅

2023-12-17 07:10 UTC, gwynne commented
One more nit: Why do it on an extension when several other conformances are already on the initial declaration?

2023-12-18 15:54 UTC, 0xTim requested changes

2023-12-18 15:54 UTC, 0xTim commented on Sources/RoutingKit/PathComponent.swift
> +extension PathComponent: Hashable {}
Agreed, let's just add this to the type declaration

2023-12-22 09:14 UTC, 0xTim approved these changes

2023-12-22 09:46 UTC, gwynne approved these changes

2023-12-22 09:47 UTC, merged